### Create a new note
POST http://localhost:4001/noteapp/create-note
Content-Type: application/json

{
  "heading": "Web Development",
  "sections": [
    { "subheading": "HTML", "content": "Learn basics of HTML" },
    { "subheading": "CSS", "content": "Learn basics of CSS" }
  ]
}

### Get all notes
GET http://localhost:4001/noteapp/get-notes

### Search notes by keyword
GET http://localhost:4001/noteapp/search/cds

### Update a note by ID
PUT http://localhost:4001/noteapp/update-note/68d2940af04a776ea4fc33b9
Content-Type: application/json

{
  "heading": "Updated Web Dev",
  "sections": [
    { "subheading": "HTML", "content": "Updated HTML content" }
  ]
}

### Delete a note by ID
DELETE http://localhost:4001/noteapp/delete-note/68d2940af04a776ea4fc33b9


